### PR TITLE
Refactored code to follow PEP8 and removed unused dependencies

### PR DESCRIPTION
**Pull request by Bear-03**

### CODE REVIEW

**Comment by waydeb** [comment]
some deps like aiohttp, discord-py-slash-command are required and can't be removed.

I'll do some additional reviewing in a few hours, please make sure these are fixed

**Comment by Bear-03** [comment]
It'll be fixed in the next commit. What's the cause though?

**Comment by waydeb** [comment]
discord-py-slash-commands is required for the slash commnads to work
aiohttp, incase users wish to set up custom commands with testing in eval pulling straight from the pihole api

**Comment by waydeb** [comment]
looks good to me. approved

**Pull request merged**
